
spring.application.name=TasteFind
spring.jpa.hibernate.ddl-auto=update

spring.datasource.url =jdbc:mysql://localhost:3306/TasteFind

spring.datasource.username=root
spring.datasource.password=147963
spring.jpa.show-sql=true